### ISSUE TITLE
Add option to disable out of tune hitsounds or hitsounds alltogether

### ISSUE THREAD

**Issue by isyy** [bemusic/bemuse#451]
as someone who plays rhythm games with hitsounds muted, this effect is extremely jarring and makes bemuse pretty unplayable for me :(

**Comment by dtinth** [comment]
This jarring effect is intentional…

Have you adjusted your audio-input latency offset? If not, I recommend that you calibrate your audio-input latency. This can improve the score and reduce this effect a lot.

These information would me useful for me to improve the game:

- What song levels do you play?
- After playing a familiar song, what accuracy data did you get? [See here for more info about accuracy data](https://qiita.com/dtinth/items/5b9f6b876a0a777eec50#the-accuracy-data), you can find it by clicking the accuracy number in the result screen.

**Comment by isyy** [comment]
Its not just about me alone having shit accuracy (im used to 4k games so 7k is a bit difficult for me, 5k i can manage however), its that jarring effects like that are a bad thing because beginners in vsrgs wont have good acc, as acc is developed alongside skill. at least make it toggleable, some people hate stuff like that anyways.

**Comment by dtinth** [comment]
I am updating the game to have [a more relaxed judgment scheme on lower-level songs](https://github.com/bemusic/bemuse/pull/446) (which increases gradually with each level), so this effect will be reduced.

I want the players to feel like they’re actually playing the music, not just tapping to the beats of the song. So, if they don’t hit the note accurately, it’s _supposed_ to sound jarring.

So for me the solution isn’t an option to disable hitsound effects (that’d be like playing a muted piano to a music), but provide a way to help beginners motivated to develop their rhythm gaming skills.

**Comment by dtinth** [comment]
I am marking this issue as closed, because I don’t have any plan to disable keysound effects.
